# Ejemplo 02

En este ejemplo crearemos un sistema de regresión polinomial: Utilizaremos los grados de un polinomio para curvear la línea (o el plano) y evaluar que tal mejora una predicción

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_squared_error

In [5]:
boston_dataset = load_boston()
bostonDataFrame = pd.DataFrame(boston_dataset.data, columns=boston_dataset.feature_names)
bostonDataFrame['MEDV'] = boston_dataset.target
X = bostonDataFrame[['LSTAT', 'RM']]
Y = bostonDataFrame['MEDV']
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.4)

### Ejemplo lineal:
Primero probaremos con predicciones lineales

In [6]:
lin_model = LinearRegression()
lin_model.fit(X_train, Y_train)
y_train_predict = lin_model.predict(X_train)
MSE = mean_squared_error(Y_train,y_train_predict)
print("Entrenamiento: MSE ="+str(MSE))

y_test_predict = lin_model.predict(X_test)
MSE = (mean_squared_error(Y_test, y_test_predict))
print("Pruebas: MSE ="+str(MSE))

df_predicciones = pd.DataFrame({'valor_real':Y_test, 'prediccion':y_test_predict, 'diferencia':Y_test-y_test_predict})
df_predicciones = df_predicciones.reset_index(drop = True)
df_predicciones.head(10)

Entrenamiento: MSE =27.848989524596842
Pruebas: MSE =35.02148193171412

   valor_real  prediccion  diferencia
0        21.4   22.636146   -1.236146
1        13.4   16.581412   -3.181412
2        20.0   18.762216    1.237784
3        19.6   22.941739   -3.341739
4        23.1   24.427308   -1.327308
5        16.2   16.154536    0.045464
6        14.6    3.610760   10.989240
7        18.5   14.817992    3.682008
8        13.6   16.993392   -3.393392
9        17.5   17.002229    0.497771

### Ejemplo de polinomio de grado 2
Ahora probaremos con un polinomio de grado 2

In [7]:
poly_model = LinearRegression()
poly = PolynomialFeatures(degree=2)

Xpolytrain = poly.fit_transform(X_train)
Xpolytest = poly.fit_transform(X_test)

poly_model.fit(Xpolytrain, Y_train)
y_train_predict = poly_model.predict(Xpolytrain)

MSE = mean_squared_error(Y_train,y_train_predict)
print("Entrenamiento: MSE ="+str(MSE))

y_test_predict = poly_model.predict(Xpolytest)
MSE = (mean_squared_error(Y_test, y_test_predict))
print("Pruebas: MSE ="+str(MSE))

df_predicciones = pd.DataFrame({'valor_real':Y_test, 'prediccion':y_test_predict, 'diferencia':Y_test-y_test_predict})
df_predicciones = df_predicciones.reset_index(drop = True)
df_predicciones.head(10)

Entrenamiento: MSE =20.6035876339334
Pruebas: MSE =20.73109193466297

   valor_real  prediccion  diferencia
0        21.4   21.242792    0.157208
1        13.4   12.751130    0.648870
2        20.0   18.288925    1.711075
3        19.6   22.466176   -2.866176
4        23.1   22.852479    0.247521
5        16.2   16.190515    0.009485
6        14.6   13.401655    1.198345
7        18.5   15.453336    3.046664
8        13.6   15.695916   -2.095916
9        17.5   17.530889   -0.030889